<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="book.aspx.cs" Inherits="NextGen_Application_Bookauthor_ForntEnd.book" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <asp:Image ID="Image1" runat="server" Height="344px" ImageUrl="~/ImageUrl/book-collage-with-15-covers.png" Width="1071px" />
    </div>
    <marquee style="color: aqua"><h2>"Here You Update,Insert and delete BooksRecord"</h2></marquee>
    <asp:HyperLink NavigateUrl="~/AddBook" Text="ADD NEW BOOKS" runat="server" BackColor="Yellow" ForeColor="Black" />
    <br />
    <br />
    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />

    <asp:GridView ID="GridView1" runat="server"
        ItemType="NextGen_Application_BookAuthor.Book" DataKeyNames="Bid"
        SelectMethod="GetBook"
        UpdateMethod="UpdateBook"
        DeleteMethod="DeleteBook"
        AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True"
        AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" EnableTheming="True" AllowPaging="True" Width="1243px"
        OnCallingDataMethods="Book_CallingDataMethods"
        GridLines="None">
        <AlternatingRowStyle BackColor="White" />
        <Columns>

            <asp:DynamicField DataField="BookName" />
            <asp:DynamicField DataField="Genre" />
            <asp:DynamicField DataField="Publication" />
            <asp:DynamicField DataField="Description" />
           


        </Columns>
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
        <SortedAscendingCellStyle BackColor="#FDF5AC" />
        <SortedAscendingHeaderStyle BackColor="#4D0000" />
        <SortedDescendingCellStyle BackColor="#FCF6C0" />
        <SortedDescendingHeaderStyle BackColor="#820000" />
    </asp:GridView>



</asp:Content>
